### ISSUE TITLE
No *.m4a for me

### ISSUE THREAD

**Issue by devkick** [ray-lothian/extractor#7]
After a fresh Firefox/Plugin(new) reinstall i get a *.acc (BASH) file. Any tips to the right settings?
Thank you very much.

**Comment by vmazoyer** [comment]
The following settings work for me to get m4a files, even tho the resulting file name is *.aac.m4a:

- Installed both native client and FFmpeg
- Remove downloaded file(s) after successful conversion: No
- Post processing: extract audio
- FFmpeg Commands - Audio Extraction: `-loglevel error -i %input -bsf:a aac_adtstoasc -codec: copy -acodec copy -vn %output.m4a`

Hope it helps

**Comment by devkick** [comment]
Your solution works fine. A DASH file still exists. Thank you very much.
